language: php

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - AWS_KEY:
    - AWS_SECRET:

php:
  - 5.6
  - 7.0
  - 7.1

before_script:
  - composer self-update && composer install --prefer-source --no-interaction

script:
  - php bin/phpspec run -fpretty --verbose
  - php bin/phpunit --verbose tests/
